project:
  type: website
  output-dir: docs
website:
  title: "Creo Hsia"
  navbar:
    background: "#F8F2FF"
    right:
      - text: 'Blogs'
        href: blog.qmd
      - icon: twitter
        href: https://x.com/CreoHAHAHA
      - icon: github
        href: https://github.com/CreoHsia
      - icon: envelope
        href: mailto:creoxjz@gmail.com
format:
  html:
    theme: cosmo
    highlight-style: breeze
    css: styles.css
    

editor: visual

