project:
  type: website
website:
  title: "Creo Hsia"
  navbar:
    right:
      - text: 'About'
        href: about.qmd
      - icon: github
        href: https://github.com/CreoHsia
      - icon: envelope
        href: mailto:creoxjz@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

